name: Auto Deploy Blue Green

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 192.168.1.25          # SERVER IP
          username: kalbi             # SERVER USER
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            echo "ğŸ“‚ Move to project directory"
            cd /home/kalbi/kalbi-testing

            echo "ğŸ”„ Pull latest code"
            git pull origin main

            echo "ğŸ³ Build docker images (no cache)"
            sudo docker-compose build --no-cache

            echo "ğŸš€ Start / Update containers"
            sudo docker-compose up -d
